# Generated by Django 5.2.13 on 2026-10-04 20:24

import agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='agreement_document',
            field=models.FileField(blank=True, null=True, storage=agents.models._agreement_storage, upload_to='agent_agreements/'),
        ),
    ]
