# Generated by Django 5.2.8 on 2026-02-17 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_and_more'),
        ('listings', '0006_review_reviewimage_propertystats_propertyview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=100)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment')], max_length=50, null=True)),
                ('min_bedrooms', models.IntegerField(blank=True, null=True)),
                ('max_bedrooms', models.IntegerField(blank=True, null=True)),
                ('min_square_footage', models.IntegerField(blank=True, null=True)),
                ('max_square_footage', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(choices=[('instantly', 'Instantly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='listings.listing')),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bookings.savedsearch')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('saved_search', 'listing')},
            },
        ),
    ]
