# Generated by Django 5.2.8 on 2026-04-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_propertycomparison_comparisonitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertycomparison',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertycomparison',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('cabin', 'Cabin'), ('cottage', 'Cottage'), ('bungalow', 'Bungalow'), ('chalet', 'Chalet'), ('treehouse', 'Treehouse'), ('boat', 'Boat'), ('castle', 'Castle'), ('cave', 'Cave'), ('farm', 'Farm')], max_length=50, null=True),
        ),
    ]
