# Generated by Django 5.2.13 on 2026-04-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_comparisonitem_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
