# Generated by Django 5.2.13 on 2026-06-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_cancelled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
