# Generated by Django 5.2.13 on 2026-06-19 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_paymentrequest_id'),
        ('listings', '0018_add_new_property_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewing_date', models.DateField(help_text='Must be a Saturday.')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('fee_paid', 'Fee Paid'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('reserved', 'Reserved'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='requested', max_length=20)),
                ('viewing_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_fee_paid', models.BooleanField(default=False)),
                ('fee_paid_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('guest_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking_per_guest_listing_dates',
        ),
        migrations.AddField(
            model_name='booking',
            name='host_confirm_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='host_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='requires_viewing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_host', 'Pending Host Confirmation'), ('awaiting_payment', 'Awaiting Payment'), ('payment_received', 'Payment Received'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('expired_unconfirmed', 'Expired (Host Did Not Confirm)'), ('expired_unpaid', 'Expired (Payment Not Completed)'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('requested', 'Requested (legacy)'), ('payment_requested', 'Payment Requested (legacy)'), ('pending', 'Pending (legacy)')], default='pending_host', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_host', 'awaiting_payment', 'payment_received', 'confirmed', 'requested', 'payment_requested', 'pending'])), fields=('customer', 'listing', 'start_date', 'end_date'), name='unique_active_booking_per_guest_listing_dates'),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewing', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewings_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='listings.listing'),
        ),
        migrations.AddConstraint(
            model_name='viewingappointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'fee_paid', 'scheduled', 'completed', 'reserved'])), fields=('listing', 'viewing_date'), name='unique_active_viewing_per_listing_date'),
        ),
    ]
