# Generated by Django 5.2.13 on 2026-07-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_viewingappointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingappointment',
            name='viewing_time',
            field=models.TimeField(blank=True, help_text='Start of the 2-hour viewing window (10:00–15:00).', null=True),
        ),
    ]
