# Generated by Django 5.2.13 on 2026-06-24 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=30)),
                ('headshot', models.ImageField(upload_to='host_applications/headshots/')),
                ('id_document', models.ImageField(upload_to='host_applications/ids/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted — Product Support review'), ('ps_approved', 'PS approved — Compliance review'), ('compliance_approved', 'Compliance approved — Supervisor review'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='submitted', max_length=25)),
                ('ps_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_stage', models.CharField(blank=True, choices=[('product_support', 'Product Support Officer'), ('compliance', 'Compliance Officer'), ('supervisor', 'Supervisor')], default='', max_length=20)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_applications', to=settings.AUTH_USER_MODEL)),
                ('compliance_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_apps_compliance_reviewed', to=settings.AUTH_USER_MODEL)),
                ('ps_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_apps_ps_reviewed', to=settings.AUTH_USER_MODEL)),
                ('supervisor_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_apps_supervisor_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('review_product_support', 'Can review host applications at the Product Support stage'), ('review_compliance', 'Can review host applications at the Compliance stage'), ('review_supervisor', 'Can review host applications at the Supervisor stage')],
            },
        ),
    ]
