# Generated by Django 5.2.16 on 2026-07-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapplications', '0004_hostapplication_ai_rationale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostapplication',
            name='next_of_kin_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='tax_clearance_receipt',
            field=models.FileField(blank=True, help_text='Updated Tax Clearance Receipt (Business Policy §4.1).', null=True, upload_to='host_applications/tax_clearance/'),
        ),
    ]
