# Generated by Django 5.2.13 on 2026-09-13 01:25

import hostapplications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapplications', '0006_rename_phone_add_momo_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostapplication',
            name='agreement_document',
            field=models.FileField(blank=True, null=True, storage=hostapplications.models._agreement_storage, upload_to='host_agreements/'),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='agreement_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
