# Generated by Django 6.0.1 on 2026-03-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_requested', 'Booking Requested'), ('booking_confirmed', 'Booking Confirmed'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('new_message', 'New Message'), ('price_changed', 'Price Changed'), ('listing_available', 'Listing Available'), ('search_alert', 'Search Alert'), ('new_review', 'New Review')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_requested_email', models.BooleanField(default=True)),
                ('booking_confirmed_email', models.BooleanField(default=True)),
                ('booking_declined_email', models.BooleanField(default=True)),
                ('booking_cancelled_email', models.BooleanField(default=True)),
                ('booking_completed_email', models.BooleanField(default=True)),
                ('payment_received_email', models.BooleanField(default=True)),
                ('payment_failed_email', models.BooleanField(default=True)),
                ('payment_refunded_email', models.BooleanField(default=True)),
                ('new_message_email', models.BooleanField(default=True)),
                ('price_changed_email', models.BooleanField(default=True)),
                ('listing_available_email', models.BooleanField(default=True)),
                ('search_alert_email', models.BooleanField(default=True)),
                ('new_review_email', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
