# Generated by Django 6.0 on 2026-04-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationpreference_phone_number_changed_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='account_reinstated_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='account_suspended_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_requested', 'Booking Requested'), ('booking_confirmed', 'Booking Confirmed'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('new_message', 'New Message'), ('price_changed', 'Price Changed'), ('listing_available', 'Listing Available'), ('search_alert', 'Search Alert'), ('new_review', 'New Review'), ('report_submitted', 'Report Submitted'), ('report_updated', 'Report Updated'), ('account_suspended', 'Account Suspended'), ('account_reinstated', 'Account Reinstated'), ('phone_number_changed', 'Phone Number Changed')], db_index=True, max_length=50),
        ),
    ]
