# Generated by Django 5.2.13 on 2026-06-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_requested', 'Booking Requested'), ('booking_submitted', 'Booking Submitted'), ('booking_confirmed', 'Booking Confirmed'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('payment_received', 'Payment Received'), ('payment_received_host', 'Payment Received (Host)'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('new_message', 'New Message'), ('price_changed', 'Price Changed'), ('listing_available', 'Listing Available'), ('search_alert', 'Search Alert'), ('new_review', 'New Review'), ('report_submitted', 'Report Submitted'), ('report_updated', 'Report Updated'), ('account_suspended', 'Account Suspended'), ('account_reinstated', 'Account Reinstated'), ('phone_number_changed', 'Phone Number Changed')], db_index=True, max_length=50),
        ),
    ]
