# Generated by Django 5.2.13 on 2026-07-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_requested', 'Booking Requested'), ('booking_submitted', 'Booking Submitted'), ('booking_confirmed', 'Booking Confirmed'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('reservation_pending_admin', 'New Reservation (Admin)'), ('booking_ready_to_pay', 'Reservation Confirmed — Pay Now'), ('payment_awaiting_admin', 'Payment Awaiting Confirmation'), ('reservation_expired', 'Reservation Expired'), ('viewing_requested', 'Viewing Requested'), ('viewing_fee_paid', 'Viewing Fee Paid'), ('viewing_scheduled', 'Viewing Scheduled'), ('payment_received', 'Payment Received'), ('payment_received_host', 'Payment Received (Host)'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('payout_pending', 'Payout Pending'), ('payout_paid', 'Payout Paid'), ('new_message', 'New Message'), ('price_changed', 'Price Changed'), ('listing_available', 'Listing Available'), ('search_alert', 'Search Alert'), ('new_review', 'New Review'), ('report_submitted', 'Report Submitted'), ('report_updated', 'Report Updated'), ('account_suspended', 'Account Suspended'), ('account_reinstated', 'Account Reinstated'), ('phone_number_changed', 'Phone Number Changed'), ('host_application_submitted', 'Host Application Submitted'), ('host_application_received', 'Host Application Received'), ('host_application_advanced', 'Host Application Advanced'), ('host_application_progress', 'Host Application Progress'), ('host_application_declined', 'Host Application Declined'), ('host_application_approved', 'Host Application Approved'), ('property_verification_submitted', 'Property Verification Submitted'), ('property_verification_advanced', 'Property Verification Advanced'), ('property_verification_received', 'Property Verification Received'), ('property_verification_progress', 'Property Verification Progress'), ('property_verification_correction', 'Property Verification Correction'), ('property_verification_rejected', 'Property Verification Rejected'), ('property_verification_published', 'Property Verification Published')], db_index=True, max_length=50),
        ),
    ]
