import type { Property, User, Review, Booking } from '../core/types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    isHost: true,
    verified: true,
    bio: 'Passionate host sharing beautiful properties',
    createdAt: '2020-01-15T00:00:00Z',
  },
  {
    id: '2',
    email: 'sarah.smith@example.com',
    firstName: 'Sarah',
    lastName: 'Smith',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    isHost: true,
    verified: true,
    bio: 'Superhost with 5+ years of experience',
    createdAt: '2019-06-10T00:00:00Z',
  },
];

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Luxurious Beachfront Villa with Infinity Pool',
    description: 'Experience paradise in this stunning beachfront villa. Wake up to breathtaking ocean views, enjoy your private infinity pool, and relax in luxurious comfort. This property features modern amenities, spacious living areas, and direct beach access.',
    propertyType: 'villa',
    category: 'beachfront',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1615873968403-89e068629265?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop',
    ],
    price: 450,
    location: {
      address: '123 Ocean Drive',
      city: 'Malibu',
      state: 'California',
      country: 'United States',
      zipCode: '90265',
      lat: 34.0259,
      lng: -118.7798,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'pool', name: 'Pool', icon: 'Waves', category: 'Outdoor' },
      { id: 'beach-access', name: 'Beach access', icon: 'Waves', category: 'Location' },
      { id: 'kitchen', name: 'Kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'ac', name: 'Air conditioning', icon: 'AirVent', category: 'Basic' },
      { id: 'parking', name: 'Free parking', icon: 'ParkingSquare', category: 'Basic' },
    ],
    bedrooms: 4,
    beds: 5,
    bathrooms: 3.5,
    guests: 8,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.9,
    reviewCount: 127,
    isSuperhost: true,
    instantBook: true,
    cancellationPolicy: 'flexible',
    houseRules: [
      'No smoking',
      'No parties or events',
      'Check-in after 3:00 PM',
      'Check-out before 11:00 AM',
    ],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 2,
    maxNights: 30,
    bookedDates: [],
    createdAt: '2023-01-10T00:00:00Z',
  },
  {
    id: '2',
    title: 'Cozy Mountain Cabin with Stunning Views',
    description: 'Escape to the mountains in this charming cabin. Perfect for nature lovers, featuring floor-to-ceiling windows, a wood-burning fireplace, and a spacious deck overlooking pristine wilderness.',
    propertyType: 'cabin',
    category: 'cabins',
    images: [
      'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1518481612222-68bbe828ecd1?w=1200&h=800&fit=crop',
    ],
    price: 185,
    location: {
      address: '456 Mountain Road',
      city: 'Aspen',
      state: 'Colorado',
      country: 'United States',
      zipCode: '81611',
      lat: 39.1911,
      lng: -106.8175,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'fireplace', name: 'Fireplace', icon: 'Flame', category: 'Indoor' },
      { id: 'kitchen', name: 'Kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'heating', name: 'Heating', icon: 'Flame', category: 'Basic' },
      { id: 'parking', name: 'Free parking', icon: 'ParkingSquare', category: 'Basic' },
    ],
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    guests: 4,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.95,
    reviewCount: 89,
    isSuperhost: true,
    instantBook: false,
    cancellationPolicy: 'moderate',
    houseRules: [
      'No smoking',
      'Pets allowed with prior approval',
      'Quiet hours after 10 PM',
    ],
    checkIn: '16:00',
    checkOut: '10:00',
    minNights: 3,
    maxNights: 14,
    bookedDates: [],
    createdAt: '2023-02-15T00:00:00Z',
  },
  {
    id: '3',
    title: 'Modern Downtown Loft with City Views',
    description: 'Stylish loft in the heart of the city. Features industrial-chic design, high ceilings, and panoramic city views. Walking distance to restaurants, shops, and nightlife.',
    propertyType: 'apartment',
    category: 'design',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=1200&h=800&fit=crop',
    ],
    price: 220,
    location: {
      address: '789 Broadway',
      city: 'New York',
      state: 'New York',
      country: 'United States',
      zipCode: '10003',
      lat: 40.7128,
      lng: -74.0060,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'workspace', name: 'Dedicated workspace', icon: 'Laptop', category: 'Work' },
      { id: 'gym', name: 'Gym', icon: 'Dumbbell', category: 'Facilities' },
      { id: 'ac', name: 'Air conditioning', icon: 'AirVent', category: 'Basic' },
      { id: 'ev-charger', name: 'EV charger', icon: 'Zap', category: 'Parking' },
    ],
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.85,
    reviewCount: 156,
    isSuperhost: true,
    instantBook: true,
    cancellationPolicy: 'strict',
    houseRules: ['No smoking', 'No pets', 'No parties'],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 1,
    maxNights: 90,
    bookedDates: [],
    createdAt: '2023-03-20T00:00:00Z',
  },
  {
    id: '4',
    title: 'Charming Countryside Cottage',
    description: 'Peaceful retreat in the countryside. This charming cottage offers tranquility and natural beauty, perfect for a relaxing getaway.',
    propertyType: 'cottage',
    category: 'countryside',
    images: [
      'https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&h=800&fit=crop',
    ],
    price: 150,
    location: {
      address: '321 Country Lane',
      city: 'Napa',
      state: 'California',
      country: 'United States',
      zipCode: '94558',
      lat: 38.2975,
      lng: -122.2869,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'kitchen', name: 'Kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'bbq', name: 'BBQ grill', icon: 'Flame', category: 'Outdoor' },
      { id: 'parking', name: 'Free parking', icon: 'ParkingSquare', category: 'Basic' },
    ],
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 6,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.8,
    reviewCount: 64,
    isSuperhost: false,
    instantBook: false,
    cancellationPolicy: 'flexible',
    houseRules: ['No smoking', 'Pets allowed'],
    checkIn: '14:00',
    checkOut: '10:00',
    minNights: 2,
    maxNights: 21,
    bookedDates: [],
    createdAt: '2023-04-05T00:00:00Z',
  },
  {
    id: '5',
    title: 'Tropical Paradise with Private Pool',
    description: 'Luxurious tropical getaway featuring a private pool, outdoor dining area, and lush gardens. Perfect for families or groups.',
    propertyType: 'villa',
    category: 'amazing-pools',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop',
    ],
    price: 380,
    location: {
      address: '555 Palm Avenue',
      city: 'Miami',
      state: 'Florida',
      country: 'United States',
      zipCode: '33139',
      lat: 25.7617,
      lng: -80.1918,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'pool', name: 'Pool', icon: 'Waves', category: 'Outdoor' },
      { id: 'hot-tub', name: 'Hot tub', icon: 'Bath', category: 'Outdoor' },
      { id: 'kitchen', name: 'Kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'ac', name: 'Air conditioning', icon: 'AirVent', category: 'Basic' },
      { id: 'bbq', name: 'BBQ grill', icon: 'Flame', category: 'Outdoor' },
    ],
    bedrooms: 5,
    beds: 6,
    bathrooms: 4,
    guests: 10,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.92,
    reviewCount: 203,
    isSuperhost: true,
    instantBook: true,
    cancellationPolicy: 'moderate',
    houseRules: ['No smoking', 'No parties', 'Pets allowed'],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 3,
    maxNights: 30,
    bookedDates: [],
    createdAt: '2023-05-12T00:00:00Z',
  },
  {
    id: '6',
    title: 'Lakefront Retreat with Dock',
    description: 'Serene lakefront property with private dock. Enjoy kayaking, fishing, and stunning sunset views over the water.',
    propertyType: 'house',
    category: 'lakefront',
    images: [
      'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&h=800&fit=crop',
    ],
    price: 275,
    location: {
      address: '888 Lake Shore Drive',
      city: 'Lake Tahoe',
      state: 'California',
      country: 'United States',
      zipCode: '96150',
      lat: 39.0968,
      lng: -120.0324,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'kitchen', name: 'Kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'fireplace', name: 'Fireplace', icon: 'Flame', category: 'Indoor' },
      { id: 'parking', name: 'Free parking', icon: 'ParkingSquare', category: 'Basic' },
    ],
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 6,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.88,
    reviewCount: 112,
    isSuperhost: true,
    instantBook: false,
    cancellationPolicy: 'flexible',
    houseRules: ['No smoking', 'Pets allowed with prior approval'],
    checkIn: '16:00',
    checkOut: '10:00',
    minNights: 2,
    maxNights: 21,
    bookedDates: [],
    createdAt: '2023-06-18T00:00:00Z',
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    propertyId: '1',
    userId: '3',
    user: {
      id: '3',
      email: 'mike@example.com',
      firstName: 'Mike',
      lastName: 'Johnson',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
      isHost: false,
      verified: true,
      createdAt: '2022-01-01T00:00:00Z',
    },
    rating: 5,
    cleanliness: 5,
    accuracy: 5,
    checkIn: 5,
    communication: 5,
    location: 5,
    value: 5,
    comment: 'Absolutely stunning property! The views were even better than the photos. John was a fantastic host and very responsive. Would definitely stay here again!',
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: '2',
    propertyId: '1',
    userId: '4',
    user: {
      id: '4',
      email: 'emma@example.com',
      firstName: 'Emma',
      lastName: 'Wilson',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
      isHost: false,
      verified: true,
      createdAt: '2022-03-15T00:00:00Z',
    },
    rating: 5,
    cleanliness: 5,
    accuracy: 5,
    checkIn: 5,
    communication: 5,
    location: 5,
    value: 4,
    comment: 'Perfect getaway! The infinity pool is incredible and the beach access made it so convenient. Highly recommend!',
    createdAt: '2024-01-22T00:00:00Z',
  },
];
