# Generated by Django 5.2.13 on 2026-07-08 19:55

import django.db.models.deletion
import propertyverifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0020_listing_lease_term_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(choices=[('owner', 'Owner'), ('non_owner', 'Non-Owner (MOU)')], max_length=20)),
                ('owner_name', models.CharField(max_length=255)),
                ('property_location', models.CharField(max_length=500)),
                ('deed_volume_number', models.CharField(max_length=100)),
                ('mou_document', models.FileField(blank=True, null=True, storage=propertyverifications.models._mou_storage, upload_to='property_verifications/mou/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted — Product Support review'), ('ps_approved', 'PS approved — Compliance review'), ('compliance_approved', 'Compliance approved — Supervisor review'), ('approved', 'Approved & Published'), ('rejected', 'Rejected'), ('correction_requested', 'Correction Requested')], db_index=True, default='submitted', max_length=25)),
                ('ps_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_stage', models.CharField(blank=True, choices=[('product_support', 'Product Support Officer'), ('compliance', 'Compliance Officer'), ('supervisor', 'Supervisor')], default='', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('resubmission_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_verifications', to=settings.AUTH_USER_MODEL)),
                ('compliance_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_verifs_compliance_reviewed', to=settings.AUTH_USER_MODEL)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='listings.listing')),
                ('ps_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_verifs_ps_reviewed', to=settings.AUTH_USER_MODEL)),
                ('supervisor_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_verifs_supervisor_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('review_property_product_support', 'Can review property verifications at the Product Support stage'), ('review_property_compliance', 'Can review property verifications at the Compliance stage'), ('review_property_supervisor', 'Can review property verifications at the Supervisor stage')],
            },
        ),
    ]
