# Generated by Django 5.2.13 on 2026-07-11 01:00

import propertyverifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyverifications', '0002_grant_group_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyverification',
            name='due_diligence_done',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyverification',
            name='inspection_report',
            field=models.FileField(blank=True, null=True, storage=propertyverifications.models._mou_storage, upload_to='property_verifications/inspections/'),
        ),
    ]
