# Generated by Django 5.2.16 on 2026-07-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyverifications', '0003_propertyverification_due_diligence_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyverification',
            name='ai_rationale',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='propertyverification',
            name='ai_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
