# Generated by Django 5.2.16 on 2026-07-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyverifications', '0004_propertyverification_ai_rationale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyverification',
            name='inspection_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propertyverification',
            name='inspection_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
