# Generated by Django 5.2.13 on 2026-08-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyverifications', '0005_propertyverification_inspection_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyverification',
            name='owner_authorization_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyverification',
            name='ownership_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('non_owner', 'Non-Owner (MOU)'), ('agent', 'Agent-Sourced')], max_length=20),
        ),
    ]
