# Generated by Django 5.2.16 on 2026-07-12 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('privacy_policy', 'Privacy Policy')], db_index=True, max_length=30)),
                ('version', models.CharField(help_text='e.g. "2026-07-12" or "v3"', max_length=30)),
                ('effective_date', models.DateField()),
                ('summary_of_changes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_documents_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document_key', 'version'), name='unique_document_version')],
            },
        ),
    ]
