# Generated by Django 5.2.16 on 2026-07-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='body_sections',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "...", "intro": "...", "content": "..." | ["...", "..."], "outro": "..."}, ...]'),
        ),
    ]
