import type { Property, User, Review } from '../core/types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    isHost: true,
    verified: true,
    bio: 'Passionate host sharing beautiful properties',
    createdAt: '2020-01-15T00:00:00Z',
  },
  {
    id: '2',
    email: 'sarah.smith@example.com',
    firstName: 'Sarah',
    lastName: 'Smith',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    isHost: true,
    verified: true,
    bio: 'Superhost with 5+ years of experience',
    createdAt: '2019-06-10T00:00:00Z',
  },
];

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Luxurious Beachfront Villa with Infinity Pool',
    description: 'Experience paradise in this stunning beachfront villa. Wake up to breathtaking ocean views, enjoy your private infinity pool, and relax in luxurious comfort. This property features modern amenities, spacious living areas, and direct beach access.',
    propertyType: 'villa',
    category: 'beachfront',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1615873968403-89e068629265?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop',
    ],
    price: 450,
    location: {
      address: '123 Ocean Drive',
      city: 'Malibu',
      state: 'California',
      country: 'United States',
      zipCode: '90265',
      lat: 34.0259,
      lng: -118.7798,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'pool', name: 'Pool', icon: 'Waves', category: 'Outdoor' },
      { id: 'beach-access', name: 'Beach access', icon: 'Waves', category: 'Location' },
      { id: 'kitchen', name: 'Kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'ac', name: 'Air conditioning', icon: 'AirVent', category: 'Basic' },
      { id: 'parking', name: 'Free parking', icon: 'ParkingSquare', category: 'Basic' },
    ],
    bedrooms: 4,
    beds: 5,
    bathrooms: 3.5,
    guests: 8,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.9,
    reviewCount: 127,
    isSuperhost: true,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'flexible',
    houseRules: [
      'No smoking',
      'No parties or events',
      'Check-in after 3:00 PM',
      'Check-out before 11:00 AM',
    ],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 2,
    maxNights: 30,
    bookedDates: [],
    createdAt: '2023-01-10T00:00:00Z',
  },
  {
    id: '2',
    title: 'Cozy Mountain Cabin with Stunning Views',
    description: 'Escape to the mountains in this charming cabin. Perfect for nature lovers, featuring floor-to-ceiling windows, a wood-burning fireplace, and a spacious deck overlooking pristine wilderness.',
    propertyType: 'cabin',
    category: 'cabins',
    images: [
      'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1518481612222-68bbe828ecd1?w=1200&h=800&fit=crop',
    ],
    price: 185,
    location: {
      address: '456 Mountain Road',
      city: 'Aspen',
      state: 'Colorado',
      country: 'United States',
      zipCode: '81611',
      lat: 39.1911,
      lng: -106.8175,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'fireplace', name: 'Fireplace', icon: 'Flame', category: 'Indoor' },
      { id: 'kitchen', name: 'Kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'heating', name: 'Heating', icon: 'Flame', category: 'Basic' },
      { id: 'parking', name: 'Free parking', icon: 'ParkingSquare', category: 'Basic' },
    ],
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    guests: 4,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.95,
    reviewCount: 89,
    isSuperhost: true,
    instantBook: false,
    selfCheckin: false,
    cancellationPolicy: 'moderate',
    houseRules: [
      'No smoking',
      'Pets allowed with prior approval',
      'Quiet hours after 10 PM',
    ],
    checkIn: '16:00',
    checkOut: '10:00',
    minNights: 3,
    maxNights: 14,
    bookedDates: [],
    createdAt: '2023-02-15T00:00:00Z',
  },
  {
    id: '3',
    title: 'Modern Downtown Loft with City Views',
    description: 'Stylish loft in the heart of the city. Features industrial-chic design, high ceilings, and panoramic city views. Walking distance to restaurants, shops, and nightlife.',
    propertyType: 'apartment',
    category: 'design',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=1200&h=800&fit=crop',
    ],
    price: 220,
    location: {
      address: '789 Broadway',
      city: 'New York',
      state: 'New York',
      country: 'United States',
      zipCode: '10003',
      lat: 40.7128,
      lng: -74.0060,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'workspace', name: 'Dedicated workspace', icon: 'Laptop', category: 'Work' },
      { id: 'gym', name: 'Gym', icon: 'Dumbbell', category: 'Facilities' },
      { id: 'ac', name: 'Air conditioning', icon: 'AirVent', category: 'Basic' },
      { id: 'ev-charger', name: 'EV charger', icon: 'Zap', category: 'Parking' },
    ],
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.85,
    reviewCount: 156,
    isSuperhost: true,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'strict',
    houseRules: ['No smoking', 'No pets', 'No parties'],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 1,
    maxNights: 90,
    bookedDates: [],
    createdAt: '2023-03-20T00:00:00Z',
  },
  {
    id: '4',
    title: 'Charming Countryside Cottage',
    description: 'Peaceful retreat in the countryside. This charming cottage offers tranquility and natural beauty, perfect for a relaxing getaway.',
    propertyType: 'cottage',
    category: 'countryside',
    images: [
      'https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&h=800&fit=crop',
    ],
    price: 150,
    location: {
      address: '321 Country Lane',
      city: 'Napa',
      state: 'California',
      country: 'United States',
      zipCode: '94558',
      lat: 38.2975,
      lng: -122.2869,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'kitchen', name: 'Kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'bbq', name: 'BBQ grill', icon: 'Flame', category: 'Outdoor' },
      { id: 'parking', name: 'Free parking', icon: 'ParkingSquare', category: 'Basic' },
    ],
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 6,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.8,
    reviewCount: 64,
    isSuperhost: false,
    instantBook: false,
    selfCheckin: false,
    cancellationPolicy: 'flexible',
    houseRules: ['No smoking', 'Pets allowed'],
    checkIn: '14:00',
    checkOut: '10:00',
    minNights: 2,
    maxNights: 21,
    bookedDates: [],
    createdAt: '2023-04-05T00:00:00Z',
  },
  {
    id: '5',
    title: 'Tropical Paradise with Private Pool',
    description: 'Luxurious tropical getaway featuring a private pool, outdoor dining area, and lush gardens. Perfect for families or groups.',
    propertyType: 'villa',
    category: 'amazing-pools',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop',
    ],
    price: 380,
    location: {
      address: '555 Palm Avenue',
      city: 'Miami',
      state: 'Florida',
      country: 'United States',
      zipCode: '33139',
      lat: 25.7617,
      lng: -80.1918,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'pool', name: 'Pool', icon: 'Waves', category: 'Outdoor' },
      { id: 'hot-tub', name: 'Hot tub', icon: 'Bath', category: 'Outdoor' },
      { id: 'kitchen', name: 'Kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'ac', name: 'Air conditioning', icon: 'AirVent', category: 'Basic' },
      { id: 'bbq', name: 'BBQ grill', icon: 'Flame', category: 'Outdoor' },
    ],
    bedrooms: 5,
    beds: 6,
    bathrooms: 4,
    guests: 10,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.92,
    reviewCount: 203,
    isSuperhost: true,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'moderate',
    houseRules: ['No smoking', 'No parties', 'Pets allowed'],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 3,
    maxNights: 30,
    bookedDates: [],
    createdAt: '2023-05-12T00:00:00Z',
  },
  {
    id: '6',
    title: 'Lakefront Retreat with Dock',
    description: 'Serene lakefront property with private dock. Enjoy kayaking, fishing, and stunning sunset views over the water.',
    propertyType: 'house',
    category: 'lakefront',
    images: [
      'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&h=800&fit=crop',
    ],
    price: 275,
    location: {
      address: '888 Lake Shore Drive',
      city: 'Lake Tahoe',
      state: 'California',
      country: 'United States',
      zipCode: '96150',
      lat: 39.0968,
      lng: -120.0324,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'kitchen', name: 'Kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'fireplace', name: 'Fireplace', icon: 'Flame', category: 'Indoor' },
      { id: 'parking', name: 'Free parking', icon: 'ParkingSquare', category: 'Basic' },
    ],
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    guests: 6,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.88,
    reviewCount: 112,
    isSuperhost: true,
    instantBook: false,
    selfCheckin: false,
    cancellationPolicy: 'flexible',
    houseRules: ['No smoking', 'Pets allowed with prior approval'],
    checkIn: '16:00',
    checkOut: '10:00',
    minNights: 2,
    maxNights: 21,
    bookedDates: [],
    createdAt: '2023-06-18T00:00:00Z',
  },
  {
    id: '7',
    title: 'Cozy Private Room in Historic Brownstone',
    description: 'Charming private room in a beautifully restored brownstone. Enjoy the character of historic architecture while having modern comforts. Shared kitchen and bathroom access.',
    propertyType: 'room',
    category: 'rooms',
    images: [
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=800&fit=crop',
    ],
    price: 85,
    location: {
      address: '142 Brooklyn Ave',
      city: 'Brooklyn',
      state: 'New York',
      country: 'United States',
      zipCode: '11213',
      lat: 40.6782,
      lng: -73.9442,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'kitchen', name: 'Shared kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'workspace', name: 'Dedicated workspace', icon: 'Laptop', category: 'Work' },
    ],
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 1,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.7,
    reviewCount: 89,
    isSuperhost: false,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'flexible',
    houseRules: ['No smoking', 'Quiet hours after 10 PM', 'No guests'],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 1,
    maxNights: 30,
    bookedDates: [],
    createdAt: '2023-07-05T00:00:00Z',
  },
  {
    id: '8',
    title: 'Luxury Suite at Grand Hotel Downtown',
    description: 'Experience five-star luxury in this elegant suite featuring marble bathrooms, king-sized beds, and stunning city views. 24-hour concierge and room service available.',
    propertyType: 'suite',
    category: 'luxury',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&h=800&fit=crop',
    ],
    price: 350,
    location: {
      address: '200 Park Avenue',
      city: 'New York',
      state: 'New York',
      country: 'United States',
      zipCode: '10017',
      lat: 40.7505,
      lng: -73.9934,
    },
    amenities: [
      { id: 'wifi', name: 'High-speed Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'room-service', name: '24/7 Room service', icon: 'UtensilsCrossed', category: 'Dining' },
      { id: 'concierge', name: 'Concierge', icon: 'UserCheck', category: 'Services' },
      { id: 'spa', name: 'Spa access', icon: 'Spa', category: 'Wellness' },
      { id: 'gym', name: 'Fitness center', icon: 'Dumbbell', category: 'Facilities' },
      { id: 'ac', name: 'Climate control', icon: 'AirVent', category: 'Basic' },
    ],
    bedrooms: 1,
    beds: 1,
    bathrooms: 2,
    guests: 2,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.95,
    reviewCount: 234,
    isSuperhost: true,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'strict',
    houseRules: ['No smoking', 'No pets', 'Check-in after 3:00 PM'],
    checkIn: '15:00',
    checkOut: '12:00',
    minNights: 1,
    maxNights: 7,
    bookedDates: [],
    createdAt: '2023-08-12T00:00:00Z',
  },
  {
    id: '9',
    title: 'Spacious Family Home with Garden',
    description: 'Perfect family home with large backyard, modern kitchen, and plenty of space for everyone. Close to schools, parks, and shopping centers.',
    propertyType: 'house',
    category: 'family',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200&h=800&fit=crop',
    ],
    price: 195,
    location: {
      address: '742 Evergreen Terrace',
      city: 'Springfield',
      state: 'Illinois',
      country: 'United States',
      zipCode: '62701',
      lat: 39.7817,
      lng: -89.6501,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'kitchen', name: 'Fully equipped kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'parking', name: 'Driveway parking', icon: 'ParkingSquare', category: 'Basic' },
      { id: 'garden', name: 'Private garden', icon: 'Flower2', category: 'Outdoor' },
      { id: 'washer', name: 'Washer/Dryer', icon: 'WashingMachine', category: 'Basic' },
      { id: 'tv', name: 'Smart TV', icon: 'Tv', category: 'Entertainment' },
    ],
    bedrooms: 4,
    beds: 5,
    bathrooms: 2.5,
    guests: 8,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.8,
    reviewCount: 167,
    isSuperhost: true,
    instantBook: false,
    selfCheckin: false,
    cancellationPolicy: 'moderate',
    houseRules: ['No smoking', 'No parties', 'Pets allowed with approval'],
    checkIn: '16:00',
    checkOut: '10:00',
    minNights: 2,
    maxNights: 30,
    bookedDates: [],
    createdAt: '2023-09-01T00:00:00Z',
  },
  {
    id: '10',
    title: 'Modern Studio Apartment in City Center',
    description: 'Stylish studio apartment in the heart of the city. Perfect for business travelers or couples visiting the urban scene.',
    propertyType: 'apartment',
    category: 'city-center',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop',
    ],
    price: 120,
    location: {
      address: '456 Urban Street',
      city: 'Chicago',
      state: 'Illinois',
      country: 'United States',
      zipCode: '60601',
      lat: 41.8781,
      lng: -87.6298,
    },
    amenities: [
      { id: 'wifi', name: 'High-speed Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'workspace', name: 'Work desk', icon: 'Laptop', category: 'Work' },
      { id: 'kitchen', name: 'Kitchenette', icon: 'ChefHat', category: 'Basic' },
      { id: 'ac', name: 'Air conditioning', icon: 'AirVent', category: 'Basic' },
      { id: 'gym', name: 'Building gym', icon: 'Dumbbell', category: 'Facilities' },
    ],
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.6,
    reviewCount: 98,
    isSuperhost: false,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'flexible',
    houseRules: ['No smoking', 'No pets', 'Quiet after 10 PM'],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 1,
    maxNights: 90,
    bookedDates: [],
    createdAt: '2023-09-15T00:00:00Z',
  },
  {
    id: '11',
    title: 'Grand Ballroom for Events & Weddings',
    description: 'Elegant ballroom perfect for weddings, corporate events, and celebrations. Features crystal chandeliers, hardwood floors, and professional catering kitchen.',
    propertyType: 'hall',
    category: 'event-spaces',
    images: [
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=1200&h=800&fit=crop',
    ],
    price: 2500,
    location: {
      address: '1000 Celebration Blvd',
      city: 'Austin',
      state: 'Texas',
      country: 'United States',
      zipCode: '78701',
      lat: 30.2672,
      lng: -97.7431,
    },
    amenities: [
      { id: 'kitchen', name: 'Commercial kitchen', icon: 'ChefHat', category: 'Facilities' },
      { id: 'sound-system', name: 'Sound system', icon: 'Volume2', category: 'Entertainment' },
      { id: 'lighting', name: 'Professional lighting', icon: 'Lightbulb', category: 'Facilities' },
      { id: 'parking', name: 'Valet parking', icon: 'ParkingSquare', category: 'Basic' },
      { id: 'bar', name: 'Full bar setup', icon: 'Wine', category: 'Dining' },
      { id: 'staging', name: 'Stage area', icon: 'Mic', category: 'Entertainment' },
    ],
    bedrooms: 0,
    beds: 0,
    bathrooms: 4,
    guests: 200,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.9,
    reviewCount: 45,
    isSuperhost: true,
    instantBook: false,
    selfCheckin: false,
    cancellationPolicy: 'strict',
    houseRules: ['No outside catering', 'Professional event coordinator required', 'Music ends by 11 PM'],
    checkIn: '08:00',
    checkOut: '02:00',
    minNights: 1,
    maxNights: 1,
    bookedDates: [],
    createdAt: '2023-10-01T00:00:00Z',
  },
  {
    id: '12',
    title: 'Luxury Resort Villa with Ocean Views',
    description: 'Indulge in resort-style luxury with private beach access, multiple pools, spa services, and world-class dining. Perfect for special occasions and celebrations.',
    propertyType: 'resort',
    category: 'luxury-resorts',
    images: [
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1602002418082-a4443e0855b8?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1602002418945-9d3c6be6c8b8?w=1200&h=800&fit=crop',
    ],
    price: 850,
    location: {
      address: '1 Paradise Resort Drive',
      city: 'Maui',
      state: 'Hawaii',
      country: 'United States',
      zipCode: '96753',
      lat: 20.7984,
      lng: -156.3319,
    },
    amenities: [
      { id: 'pool', name: 'Multiple pools', icon: 'Waves', category: 'Outdoor' },
      { id: 'spa', name: 'Full spa services', icon: 'Spa', category: 'Wellness' },
      { id: 'beach-access', name: 'Private beach', icon: 'Waves', category: 'Location' },
      { id: 'restaurant', name: 'On-site dining', icon: 'UtensilsCrossed', category: 'Dining' },
      { id: 'concierge', name: '24/7 concierge', icon: 'UserCheck', category: 'Services' },
      { id: 'fitness', name: 'Fitness center', icon: 'Dumbbell', category: 'Facilities' },
      { id: 'wifi', name: 'High-speed Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'room-service', name: 'Room service', icon: 'UtensilsCrossed', category: 'Dining' },
    ],
    bedrooms: 3,
    beds: 4,
    bathrooms: 3,
    guests: 6,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.95,
    reviewCount: 312,
    isSuperhost: true,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'strict',
    houseRules: ['No smoking in villas', 'Pets not allowed', 'Minimum age 21'],
    checkIn: '16:00',
    checkOut: '11:00',
    minNights: 3,
    maxNights: 14,
    bookedDates: [],
    createdAt: '2023-10-15T00:00:00Z',
  },
  {
    id: '13',
    title: 'Historic Castle Tower Suite',
    description: 'Live like royalty in this restored castle tower. Features medieval architecture, modern amenities, and breathtaking views of the surrounding countryside.',
    propertyType: 'castle',
    category: 'unique-stays',
    images: [
      'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=800&fit=crop',
    ],
    price: 500,
    location: {
      address: 'Castle Hill Road',
      city: 'Edinburgh',
      state: 'Scotland',
      country: 'United Kingdom',
      zipCode: 'EH1 2NG',
      lat: 55.9533,
      lng: -3.1883,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'fireplace', name: 'Working fireplace', icon: 'Flame', category: 'Indoor' },
      { id: 'kitchen', name: 'Modern kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'parking', name: 'Castle grounds parking', icon: 'ParkingSquare', category: 'Basic' },
      { id: 'library', name: 'Private library', icon: 'BookOpen', category: 'Entertainment' },
    ],
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    guests: 4,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.9,
    reviewCount: 78,
    isSuperhost: true,
    instantBook: false,
    selfCheckin: false,
    cancellationPolicy: 'moderate',
    houseRules: ['No parties', 'Historic preservation guidelines', 'Guided tours available'],
    checkIn: '16:00',
    checkOut: '10:00',
    minNights: 2,
    maxNights: 7,
    bookedDates: [],
    createdAt: '2023-11-01T00:00:00Z',
  },
  {
    id: '14',
    title: 'Desert Land Parcel for Camping',
    description: 'Beautiful desert land perfect for camping, stargazing, and outdoor adventures. Features natural rock formations and incredible night sky views.',
    propertyType: 'land',
    category: 'camping',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1471115853179-bb1d604434e0?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=800&fit=crop',
    ],
    price: 45,
    location: {
      address: 'Desert Vista Trail',
      city: 'Joshua Tree',
      state: 'California',
      country: 'United States',
      zipCode: '92252',
      lat: 34.1347,
      lng: -116.3131,
    },
    amenities: [
      { id: 'campfire', name: 'Campfire pit', icon: 'Flame', category: 'Outdoor' },
      { id: 'parking', name: 'Primitive parking', icon: 'ParkingSquare', category: 'Basic' },
      { id: 'views', name: 'Stargazing', icon: 'Star', category: 'Location' },
      { id: 'hiking', name: 'Hiking trails', icon: 'Mountain', category: 'Outdoor' },
    ],
    bedrooms: 0,
    beds: 0,
    bathrooms: 0,
    guests: 6,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.7,
    reviewCount: 156,
    isSuperhost: false,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'flexible',
    houseRules: ['Leave no trace', 'Pack out what you pack in', 'No permanent structures', 'Campfires in designated areas only'],
    checkIn: '14:00',
    checkOut: '11:00',
    minNights: 1,
    maxNights: 14,
    bookedDates: [],
    createdAt: '2023-11-15T00:00:00Z',
  },
  {
    id: '15',
    title: 'Luxury Hotel Room with City View',
    description: 'Elegant hotel room in a boutique hotel featuring modern design, premium bedding, and stunning city skyline views. Includes complimentary breakfast.',
    propertyType: 'hotel',
    category: 'boutique-hotels',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=1200&h=800&fit=crop',
    ],
    price: 180,
    location: {
      address: '300 Boutique Hotel Ave',
      city: 'San Francisco',
      state: 'California',
      country: 'United States',
      zipCode: '94102',
      lat: 37.7749,
      lng: -122.4194,
    },
    amenities: [
      { id: 'wifi', name: 'High-speed Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'breakfast', name: 'Complimentary breakfast', icon: 'Coffee', category: 'Dining' },
      { id: 'concierge', name: 'Concierge service', icon: 'UserCheck', category: 'Services' },
      { id: 'room-service', name: 'Room service', icon: 'UtensilsCrossed', category: 'Dining' },
      { id: 'ac', name: 'Climate control', icon: 'AirVent', category: 'Basic' },
      { id: 'minibar', name: 'Minibar', icon: 'Wine', category: 'Dining' },
    ],
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guests: 2,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.8,
    reviewCount: 203,
    isSuperhost: true,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'moderate',
    houseRules: ['No smoking', 'No pets', 'Quiet hours 10 PM - 8 AM'],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 1,
    maxNights: 30,
    bookedDates: [],
    createdAt: '2023-12-01T00:00:00Z',
  },
  {
    id: '16',
    title: 'Treehouse Retreat in Redwood Forest',
    description: 'Magical treehouse nestled in ancient redwoods. Experience nature from above with modern comforts and breathtaking forest views.',
    propertyType: 'treehouse',
    category: 'unique-stays',
    images: [
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1471115853179-bb1d604434e0?w=1200&h=800&fit=crop',
    ],
    price: 225,
    location: {
      address: 'Redwood Canopy Trail',
      city: 'Redwood National Park',
      state: 'California',
      country: 'United States',
      zipCode: '95531',
      lat: 41.2132,
      lng: -124.0046,
    },
    amenities: [
      { id: 'wifi', name: 'Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'kitchen', name: 'Compact kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'deck', name: 'Private deck', icon: 'TreePine', category: 'Outdoor' },
      { id: 'hiking', name: 'Forest trails', icon: 'Mountain', category: 'Outdoor' },
      { id: 'fire-pit', name: 'Fire pit', icon: 'Flame', category: 'Outdoor' },
    ],
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 2,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.9,
    reviewCount: 89,
    isSuperhost: true,
    instantBook: false,
    selfCheckin: false,
    cancellationPolicy: 'moderate',
    houseRules: ['No smoking', 'Children 8+', 'No pets', 'Respect nature'],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 2,
    maxNights: 7,
    bookedDates: [],
    createdAt: '2023-12-15T00:00:00Z',
  },
  {
    id: '17',
    title: 'Conference Hall with AV Equipment',
    description: 'Modern conference hall perfect for business meetings, workshops, and presentations. Features state-of-the-art AV equipment and flexible seating arrangements.',
    propertyType: 'hall',
    category: 'business',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1556912173-46c336c7fd55?w=1200&h=800&fit=crop',
    ],
    price: 800,
    location: {
      address: '500 Business Center Drive',
      city: 'Seattle',
      state: 'Washington',
      country: 'United States',
      zipCode: '98101',
      lat: 47.6062,
      lng: -122.3321,
    },
    amenities: [
      { id: 'projector', name: 'Projector & screen', icon: 'Monitor', category: 'Technology' },
      { id: 'sound-system', name: 'Sound system', icon: 'Volume2', category: 'Technology' },
      { id: 'wifi', name: 'High-speed Wifi', icon: 'Wifi', category: 'Basic' },
      { id: 'catering', name: 'Catering kitchen', icon: 'ChefHat', category: 'Facilities' },
      { id: 'parking', name: 'Underground parking', icon: 'ParkingSquare', category: 'Basic' },
      { id: 'whiteboard', name: 'Whiteboards', icon: 'PenTool', category: 'Facilities' },
    ],
    bedrooms: 0,
    beds: 0,
    bathrooms: 2,
    guests: 50,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.7,
    reviewCount: 67,
    isSuperhost: false,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'moderate',
    houseRules: ['No food without catering approval', 'Clean up after use', 'Equipment must be returned to original positions'],
    checkIn: '08:00',
    checkOut: '18:00',
    minNights: 1,
    maxNights: 1,
    bookedDates: [],
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '18',
    title: 'Safari Lodge with Wildlife Views',
    description: 'Authentic safari lodge offering game drives, wildlife viewing, and luxury accommodations in the heart of the savanna.',
    propertyType: 'lodge',
    category: 'safari',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
    ],
    price: 650,
    location: {
      address: 'Savanna View Road',
      city: 'Serengeti',
      state: 'Tanzania',
      country: 'Tanzania',
      zipCode: '00000',
      lat: -2.3333,
      lng: 34.8333,
    },
    amenities: [
      { id: 'game-drives', name: 'Guided game drives', icon: 'Car', category: 'Activities' },
      { id: 'wildlife', name: 'Wildlife viewing', icon: 'Eye', category: 'Activities' },
      { id: 'restaurant', name: 'On-site dining', icon: 'UtensilsCrossed', category: 'Dining' },
      { id: 'bar', name: 'Safari bar', icon: 'Wine', category: 'Dining' },
      { id: 'pool', name: 'Plunge pool', icon: 'Waves', category: 'Outdoor' },
      { id: 'wifi', name: 'Limited Wifi', icon: 'Wifi', category: 'Basic' },
    ],
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    guests: 4,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.95,
    reviewCount: 134,
    isSuperhost: true,
    instantBook: false,
    selfCheckin: false,
    cancellationPolicy: 'strict',
    houseRules: ['Respect wildlife', 'Stay on designated paths', 'No flash photography of animals', 'Minimum age 12'],
    checkIn: '14:00',
    checkOut: '10:00',
    minNights: 3,
    maxNights: 7,
    bookedDates: [],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '19',
    title: 'Historic Lighthouse Keeper\'s Cottage',
    description: 'Charming cottage attached to a working lighthouse. Wake up to ocean views and the sound of waves. Perfect for lighthouse enthusiasts and nature lovers.',
    propertyType: 'lighthouse',
    category: 'unique-stays',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1471115853179-bb1d604434e0?w=1200&h=800&fit=crop',
    ],
    price: 175,
    location: {
      address: '1 Lighthouse Point',
      city: 'Maine Coast',
      state: 'Maine',
      country: 'United States',
      zipCode: '04614',
      lat: 44.3876,
      lng: -68.2039,
    },
    amenities: [
      { id: 'ocean-view', name: 'Ocean views', icon: 'Waves', category: 'Location' },
      { id: 'lighthouse', name: 'Lighthouse access', icon: 'Lightbulb', category: 'Unique' },
      { id: 'kitchen', name: 'Fully equipped kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'fireplace', name: 'Wood fireplace', icon: 'Flame', category: 'Indoor' },
      { id: 'parking', name: 'Private parking', icon: 'ParkingSquare', category: 'Basic' },
    ],
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    guests: 4,
    hostId: '1',
    host: mockUsers[0],
    rating: 4.8,
    reviewCount: 92,
    isSuperhost: true,
    instantBook: false,
    selfCheckin: false,
    cancellationPolicy: 'moderate',
    houseRules: ['No climbing on lighthouse', 'Respect maritime navigation', 'Weather dependent access'],
    checkIn: '16:00',
    checkOut: '10:00',
    minNights: 2,
    maxNights: 14,
    bookedDates: [],
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '20',
    title: 'Yurt Camp in Mountain Valley',
    description: 'Traditional Mongolian yurt offering a unique glamping experience. Surrounded by mountains with modern comforts and traditional design elements.',
    propertyType: 'yurt',
    category: 'glamping',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1471115853179-bb1d604434e0?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=800&fit=crop',
    ],
    price: 135,
    location: {
      address: 'Mountain Valley Glamping',
      city: 'Bozeman',
      state: 'Montana',
      country: 'United States',
      zipCode: '59715',
      lat: 45.6770,
      lng: -111.0429,
    },
    amenities: [
      { id: 'fire-pit', name: 'Fire pit', icon: 'Flame', category: 'Outdoor' },
      { id: 'kitchen', name: 'Outdoor kitchen', icon: 'ChefHat', category: 'Basic' },
      { id: 'bathroom', name: 'Composting toilet', icon: 'Bath', category: 'Basic' },
      { id: 'shower', name: 'Outdoor shower', icon: 'ShowerHead', category: 'Basic' },
      { id: 'parking', name: 'Parking area', icon: 'ParkingSquare', category: 'Basic' },
    ],
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guests: 2,
    hostId: '2',
    host: mockUsers[1],
    rating: 4.6,
    reviewCount: 78,
    isSuperhost: false,
    instantBook: true,
    selfCheckin: false,
    cancellationPolicy: 'flexible',
    houseRules: ['Leave no trace', 'Respect quiet hours', 'No smoking inside yurt'],
    checkIn: '15:00',
    checkOut: '11:00',
    minNights: 1,
    maxNights: 7,
    bookedDates: [],
    createdAt: '2024-02-15T00:00:00Z',
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    propertyId: '1',
    userId: '3',
    user: {
      id: '3',
      email: 'mike@example.com',
      firstName: 'Mike',
      lastName: 'Johnson',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
      isHost: false,
      verified: true,
      createdAt: '2022-01-01T00:00:00Z',
    },
    rating: 5,
    cleanliness: 5,
    accuracy: 5,
    checkIn: 5,
    communication: 5,
    location: 5,
    value: 5,
    comment: 'Absolutely stunning property! The views were even better than the photos. John was a fantastic host and very responsive. Would definitely stay here again!',
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: '2',
    propertyId: '1',
    userId: '4',
    user: {
      id: '4',
      email: 'emma@example.com',
      firstName: 'Emma',
      lastName: 'Wilson',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
      isHost: false,
      verified: true,
      createdAt: '2022-03-15T00:00:00Z',
    },
    rating: 5,
    cleanliness: 5,
    accuracy: 5,
    checkIn: 5,
    communication: 5,
    location: 5,
    value: 4,
    comment: 'Perfect getaway! The infinity pool is incredible and the beach access made it so convenient. Highly recommend!',
    createdAt: '2024-01-22T00:00:00Z',
  },
];
