# Generated by Django 5.2.16 on 2026-07-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustsafety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudflag',
            name='ai_rationale',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='ai_score',
            field=models.FloatField(blank=True, help_text='Populated asynchronously by the local scoring model — see aiscoring.tasks.score_fraud_flag_task.', null=True),
        ),
    ]
