# Generated by Django 5.2.16 on 2026-07-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_percent', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('memory_used_mb', models.FloatField()),
                ('memory_total_mb', models.FloatField()),
                ('disk_used_percent', models.FloatField()),
                ('disk_free_gb', models.FloatField()),
                ('net_bytes_sent_mb', models.FloatField()),
                ('net_bytes_recv_mb', models.FloatField()),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
