/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<number, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<string, Date | string, Date | string>;

export interface AgentsAgentapplication {
  address: string;
  agreement_accepted_at: Timestamp | null;
  agreement_version: string;
  applicant_id: Int8;
  compliance_reviewed_at: Timestamp | null;
  compliance_reviewed_by_id: Int8 | null;
  created_at: Timestamp;
  decline_reason: string;
  declined_stage: string;
  full_name: string;
  id: Generated<Int8>;
  id_document: string;
  phone: string;
  ps_reviewed_at: Timestamp | null;
  ps_reviewed_by_id: Int8 | null;
  status: string;
  supervisor_reviewed_at: Timestamp | null;
  supervisor_reviewed_by_id: Int8 | null;
  updated_at: Timestamp;
}

export interface AgentsAgentcommission {
  agent_id: Int8;
  amount: Numeric;
  booking_amount: Numeric;
  booking_id: Int8;
  created_at: Timestamp;
  currency: string;
  id: Generated<Int8>;
  listing_id: Int8 | null;
  notes: string;
  paid_at: Timestamp | null;
  paid_by_id: Int8 | null;
  reference: string;
  status: string;
  updated_at: Timestamp;
  voided_at: Timestamp | null;
}

export interface AgentsAgentprofile {
  application_id: Int8 | null;
  approved_at: Timestamp | null;
  id: Generated<Int8>;
  is_active: boolean;
  user_id: Int8;
}

export interface AuthappBlacklistedtoken {
  blacklisted_at: Timestamp;
  expires_at: Timestamp;
  id: Generated<Int8>;
  token: string;
}

export interface AuthappSocialaccount {
  created_at: Timestamp;
  email_at_link: string;
  id: Generated<Int8>;
  last_login_at: Timestamp | null;
  provider: string;
  provider_user_id: string;
  user_id: Int8;
}

export interface AuthGroup {
  id: Generated<number>;
  name: string;
}

export interface AuthGroupPermissions {
  group_id: number;
  id: Generated<Int8>;
  permission_id: number;
}

export interface AuthPermission {
  codename: string;
  content_type_id: number;
  id: Generated<number>;
  name: string;
}

export interface BookingsBooking {
  cancelled_at: Timestamp | null;
  confirmed_at: Timestamp | null;
  customer_id: Int8;
  decline_reason: string;
  declined_at: Timestamp | null;
  end_date: Timestamp;
  extended_at: Timestamp | null;
  extended_by_id: Int8 | null;
  extended_until: Timestamp | null;
  extension_reason: string;
  host_confirm_deadline: Timestamp | null;
  host_confirmed_at: Timestamp | null;
  hotel_room_id: Int8 | null;
  id: Generated<Int8>;
  listing_id: Int8;
  notes: string;
  owner_notes: string;
  payment_due_at: Timestamp | null;
  requested_at: Timestamp;
  requires_viewing: boolean;
  service_fee: Numeric | null;
  start_date: Timestamp;
  status: string;
  stripe_payment_intent_id: string | null;
  total_price: Numeric | null;
}

export interface BookingsComparisonitem {
  comparison_id: Int8;
  id: Generated<Int8>;
  listing_id: Int8;
  notes: string;
  order: number;
}

export interface BookingsPaymentrequest {
  amount: Numeric;
  booking_id: Int8;
  created_at: Timestamp;
  created_by_id: Int8;
  currency: string;
  id: Generated<Int8>;
  is_paid: boolean;
  notes: string;
  paid_at: Timestamp | null;
  stripe_payment_intent_id: string | null;
}

export interface BookingsPropertycomparison {
  created_at: Timestamp;
  id: Generated<Int8>;
  is_public: boolean;
  name: string;
  share_token: string | null;
  updated_at: Timestamp;
  user_id: Int8;
}

export interface BookingsSavedsearch {
  address: string;
  created_at: Timestamp;
  email_frequency: string;
  id: Generated<Int8>;
  is_active: boolean;
  is_available: boolean;
  keywords: string;
  max_bedrooms: number | null;
  max_price: Numeric | null;
  max_square_footage: number | null;
  min_bedrooms: number | null;
  min_price: Numeric | null;
  min_square_footage: number | null;
  name: string;
  property_type: string | null;
  updated_at: Timestamp;
  user_id: Int8;
}

export interface BookingsSearchalert {
  id: Generated<Int8>;
  listing_id: Int8;
  saved_search_id: Int8;
  sent_at: Timestamp;
}

export interface BookingsViewingappointment {
  admin_notes: string;
  booking_id: Int8 | null;
  confirmed_by_id: Int8 | null;
  created_at: Timestamp;
  fee_paid_at: Timestamp | null;
  guest_id: Int8;
  guest_notes: string;
  id: Generated<Int8>;
  is_fee_paid: boolean;
  listing_id: Int8;
  scheduled_at: Timestamp | null;
  status: string;
  stripe_payment_intent_id: string | null;
  updated_at: Timestamp;
  viewing_date: Timestamp;
  viewing_fee: Numeric;
  viewing_time: string | null;
}

export interface CacheTable {
  cache_key: string;
  expires: Timestamp;
  value: string;
}

export interface ChatbotChatmessage {
  content: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  role: string;
  session_id: string;
  suggested_handoff: boolean;
}

export interface ChatbotChatsession {
  created_at: Timestamp;
  handed_off: boolean;
  handoff_ticket_id: Int8 | null;
  id: string;
  session_key: string;
  updated_at: Timestamp;
  user_id: Int8 | null;
}

export interface DjangoAdminLog {
  action_flag: number;
  action_time: Timestamp;
  change_message: string;
  content_type_id: number | null;
  id: Generated<number>;
  object_id: string | null;
  object_repr: string;
  user_id: Int8;
}

export interface DjangoContentType {
  app_label: string;
  id: Generated<number>;
  model: string;
}

export interface DjangoMigrations {
  app: string;
  applied: Timestamp;
  id: Generated<Int8>;
  name: string;
}

export interface DjangoSession {
  expire_date: Timestamp;
  session_data: string;
  session_key: string;
}

export interface DjangoSite {
  domain: string;
  id: Generated<number>;
  name: string;
}

export interface HostapplicationsAgreementacceptance {
  accepted_at: Timestamp;
  agreement: string;
  id: Generated<Int8>;
  ip_address: string | null;
  user_id: Int8;
  version: string;
}

export interface HostapplicationsHostapplication {
  address: string;
  agreement_document: string | null;
  agreement_version: string;
  ai_rationale: string;
  ai_risk_score: number | null;
  applicant_id: Int8;
  compliance_reviewed_at: Timestamp | null;
  compliance_reviewed_by_id: Int8 | null;
  created_at: Timestamp;
  decline_reason: string;
  declined_stage: string;
  full_name: string;
  headshot: string;
  id: Generated<Int8>;
  id_document: string;
  momo_network: string;
  momo_number: string;
  next_of_kin_name: string;
  next_of_kin_phone: string;
  next_of_kin_relationship: string;
  ps_reviewed_at: Timestamp | null;
  ps_reviewed_by_id: Int8 | null;
  status: string;
  supervisor_reviewed_at: Timestamp | null;
  supervisor_reviewed_by_id: Int8 | null;
  tax_clearance_receipt: string | null;
  updated_at: Timestamp;
}

export interface InventoryListingflag {
  ai_rationale: string;
  ai_score: number | null;
  created_at: Timestamp;
  details: string;
  flag_type: string;
  id: Generated<Int8>;
  listing_id: Int8 | null;
  review_notes: string;
  reviewed_at: Timestamp | null;
  reviewed_by_id: Int8 | null;
  severity: string;
  status: string;
}

export interface LeaseagreementsLeaseacceptance {
  accepted_at: Timestamp;
  booking_id: Int8;
  id: Generated<Int8>;
  ip_address: string | null;
  user_id: Int8;
  version: string;
}

export interface LeaseagreementsLeaseagreement {
  booking_id: Int8;
  document: string | null;
  generated_at: Timestamp;
  id: Generated<Int8>;
  landlord_name: string;
  lease_end: Timestamp | null;
  lease_start: Timestamp | null;
  property_address: string;
  rent_display: string;
  tenant_name: string;
  updated_at: Timestamp;
  version: string;
}

export interface LegalopsLegaldocument {
  body_sections: Json;
  created_at: Timestamp;
  document_key: string;
  effective_date: Timestamp;
  id: Generated<Int8>;
  published_by_id: Int8 | null;
  summary_of_changes: string;
  version: string;
}

export interface ListingsFavorite {
  created_at: Timestamp;
  id: Generated<Int8>;
  listing_id: Int8;
  user_id: Int8;
}

export interface ListingsHotelroom {
  amenities: Json;
  bathrooms: number;
  bed_type: string;
  beds: number;
  created_at: Timestamp;
  description: string;
  id: Generated<Int8>;
  is_active: boolean;
  listing_id: Int8;
  max_occupancy: number;
  name: string;
  price_per_night: Numeric;
  room_type: string;
  total_count: number;
}

export interface ListingsHotelroomimage {
  caption: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  image: string;
  order: number;
  room_id: Int8;
}

export interface ListingsListing {
  address: string;
  agent_owner_email: string;
  agent_owner_name: string;
  agent_owner_payout_network: string;
  agent_owner_payout_number: string;
  agent_owner_phone: string;
  amenities: Json;
  bathrooms: number;
  bedrooms: number;
  beds: number;
  booking_mode: string;
  cancellation_policy: string;
  check_in_time: string;
  check_out_time: string;
  city: string;
  claimed_by_user_id: Int8 | null;
  country: string;
  created_at: Timestamp;
  deleted_at: Timestamp | null;
  description: string;
  exterior_camera: boolean;
  highlights: Json;
  id: Generated<Int8>;
  is_available: boolean;
  last_minute_discount_enabled: boolean;
  last_minute_discount_percent: number;
  latitude: Numeric | null;
  lease_term_months: number | null;
  local_registration_number: string;
  longitude: Numeric | null;
  main_image: string | null;
  max_guests: number;
  monthly_discount_enabled: boolean;
  monthly_discount_percent: number;
  new_listing_promo: boolean;
  noise_monitor: boolean;
  occupancy_cap: number | null;
  owner_id: Int8;
  payment_schedule: string | null;
  price: Numeric;
  pricing_type: string;
  privacy_type: string;
  property_type: string;
  self_checkin: boolean;
  sourced_by_agent_id: Int8 | null;
  square_footage: number;
  state: string;
  status: string;
  suspended_at: Timestamp | null;
  suspended_by_id: Int8 | null;
  suspension_reason: string;
  title: string;
  updated_at: Timestamp;
  weapons_on_property: boolean;
  weekend_premium_percent: number;
  weekly_discount_enabled: boolean;
  weekly_discount_percent: number;
}

export interface ListingsListingimage {
  caption: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  image: string;
  listing_id: Int8;
  order: number;
}

export interface ListingsListingsettings {
  id: Generated<Int8>;
  min_monthly_price: Numeric;
  updated_at: Timestamp;
}

export interface ListingsPropertycategory {
  created_at: Timestamp;
  id: Generated<Int8>;
  is_active: boolean;
  name: string;
  slug: string;
  sort_order: number;
  updated_at: Timestamp;
}

export interface ListingsPropertystats {
  bookings: number;
  date: Timestamp;
  favorites: number;
  id: Generated<Int8>;
  listing_id: Int8;
  revenue: Numeric;
  unique_views: number;
  views: number;
}

export interface ListingsPropertyview {
  id: Generated<Int8>;
  ip_address: string;
  listing_id: Int8;
  timestamp: Timestamp;
  user_agent: string;
  user_id: Int8 | null;
}

export interface ListingsReview {
  accuracy: number | null;
  check_in_rating: number | null;
  cleanliness: number | null;
  communication: number | null;
  content: string;
  created_at: Timestamp;
  host_response: string;
  host_response_at: Timestamp | null;
  id: Generated<Int8>;
  is_verified: boolean;
  listing_id: Int8;
  location_rating: number | null;
  rating: number;
  reviewer_id: Int8;
  title: string;
  updated_at: Timestamp;
  value: number | null;
}

export interface ListingsReviewimage {
  caption: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  image: string;
  review_id: Int8;
}

export interface MessagingConversation {
  created_at: Timestamp;
  id: Generated<Int8>;
  listing_id: Int8 | null;
  updated_at: Timestamp;
}

export interface MessagingConversationDeletedBy {
  conversation_id: Int8;
  id: Generated<Int8>;
  user_id: Int8;
}

export interface MessagingConversationParticipants {
  conversation_id: Int8;
  id: Generated<Int8>;
  user_id: Int8;
}

export interface MessagingMessage {
  content: string;
  conversation_id: Int8;
  created_at: Timestamp;
  edited_at: Timestamp | null;
  id: Generated<Int8>;
  is_read: boolean;
  message_type: string;
  reply_to_id: Int8 | null;
  sender_id: Int8;
  updated_at: Timestamp;
}

export interface MessagingMessageattachment {
  created_at: Timestamp;
  file: string;
  file_name: string;
  file_size: number;
  file_type: string;
  id: Generated<Int8>;
  message_id: Int8;
}

export interface MessagingMessageviolation {
  conversation_id: Int8 | null;
  created_at: Timestamp;
  id: Generated<Int8>;
  matched_label: string;
  recipient_id: Int8 | null;
  sender_id: Int8;
  violation_type: string;
}

export interface NewsletterSubscriber {
  email: string;
  first_name: string;
  id: Generated<Int8>;
  interests: Json;
  is_active: boolean;
  subscribed_at: Timestamp;
  unsubscribe_token: string;
  unsubscribed_at: Timestamp | null;
}

export interface NotificationsDevicetoken {
  auth: string;
  created_at: Timestamp;
  device_type: string;
  endpoint: string;
  id: Generated<Int8>;
  p256dh: string;
  user_id: Int8;
}

export interface NotificationsNotification {
  created_at: Timestamp;
  data: Json;
  email_sent: boolean;
  id: Generated<Int8>;
  is_read: boolean;
  message: string;
  notification_type: string;
  read_at: Timestamp | null;
  title: string;
  user_id: Int8;
}

export interface NotificationsNotificationpreference {
  account_reinstated_email: boolean;
  account_suspended_email: boolean;
  booking_cancelled_email: boolean;
  booking_completed_email: boolean;
  booking_confirmed_email: boolean;
  booking_declined_email: boolean;
  booking_requested_email: boolean;
  id: Generated<Int8>;
  in_app_enabled: boolean;
  listing_available_email: boolean;
  new_message_email: boolean;
  new_review_email: boolean;
  payment_failed_email: boolean;
  payment_received_email: boolean;
  payment_refunded_email: boolean;
  phone_number_changed_email: boolean;
  price_changed_email: boolean;
  report_submitted_email: boolean;
  report_updated_email: boolean;
  search_alert_email: boolean;
  updated_at: Timestamp;
  user_id: Int8;
}

export interface PaymentsCurrency {
  code: string;
  created_at: Timestamp;
  exchange_rate_to_usd: Numeric;
  id: Generated<Int8>;
  is_active: boolean;
  name: string;
  symbol: string;
  updated_at: Timestamp;
}

export interface PaymentsEmployee {
  created_at: Timestamp;
  id: Generated<Int8>;
  is_active: boolean;
  momo_network: string;
  momo_number: string;
  name: string;
  role_title: string;
  updated_at: Timestamp;
}

export interface PaymentsEmployeepayment {
  amount: Numeric;
  created_at: Timestamp;
  currency: string;
  description: string;
  employee_id: Int8;
  error_message: string;
  id: string;
  paid_by_id: Int8 | null;
  reference: string;
  status: string;
}

export interface PaymentsEscrowhold {
  booking_id: Int8;
  held_at: Timestamp;
  held_by_id: Int8 | null;
  id: Generated<Int8>;
  reason: string;
  released_at: Timestamp | null;
  released_by_id: Int8 | null;
}

export interface PaymentsPayment {
  amount: Numeric;
  amount_in_usd: Numeric;
  booking_id: Int8 | null;
  card_country: string;
  card_last4: string;
  card_type: string;
  completed_at: Timestamp | null;
  created_at: Timestamp;
  currency_id: Int8;
  gateway_id: Int8;
  gateway_response: Json;
  gateway_transaction_id: string;
  id: string;
  network_provider: string;
  payment_method: string;
  phone_number: string;
  processed_at: Timestamp | null;
  purpose: string;
  status: string;
  user_id: Int8;
  viewing_id: Int8 | null;
}

export interface PaymentsPaymentgateway {
  api_key: string;
  business_number: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  is_active: boolean;
  live_url: string;
  merchant_id: string;
  name: string;
  sandbox_mode: boolean;
  sandbox_url: string;
  secret_key: string;
  updated_at: Timestamp;
  webhook_secret: string;
}

export interface PaymentsPayout {
  booking_id: Int8;
  cancellation_reason: string;
  cancelled_at: Timestamp | null;
  cancelled_by_id: Int8 | null;
  created_at: Timestamp;
  currency: string;
  gross_amount: Numeric;
  host_id: Int8;
  id: string;
  net_amount: Numeric;
  notes: string;
  paid_at: Timestamp | null;
  paid_by_id: Int8 | null;
  recipient_momo_number: string;
  recipient_name: string;
  recipient_network: string;
  reference: string;
  service_fee_amount: Numeric;
  status: string;
  updated_at: Timestamp;
}

export interface PaymentsPlatformfee {
  agent_commission_percent: Numeric;
  id: Generated<Int8>;
  service_fee_percent: Numeric;
  transaction_fee_max: Numeric | null;
  transaction_fee_min: Numeric | null;
  transaction_fee_type: string;
  transaction_fee_value: Numeric;
  updated_at: Timestamp;
  viewing_fee: Numeric;
}

export interface PaymentsRefund {
  amount: Numeric;
  created_at: Timestamp;
  gateway_refund_id: string;
  id: Generated<Int8>;
  payment_id: string;
  processed_at: Timestamp | null;
  reason: string;
  reason_code: string;
  status: string;
}

export interface PaymentsSavedcard {
  card_type: string;
  cardholder_name: string;
  created_at: Timestamp;
  expiry_month: string;
  expiry_year: string;
  id: Generated<Int8>;
  is_default: boolean;
  last4: string;
  user_id: Int8;
}

export interface PaymentsStriperefund {
  amount: Numeric;
  booking_id: Int8;
  created_at: Timestamp;
  error_message: string;
  id: Generated<Int8>;
  initiated_by_id: Int8 | null;
  reason: string;
  reason_code: string;
  status: string;
  stripe_payment_intent_id: string;
  stripe_refund_id: string;
}

export interface PaymentsTaxrate {
  created_at: Timestamp;
  created_by_id: Int8 | null;
  id: Generated<Int8>;
  is_active: boolean;
  jurisdiction: string;
  rate_percent: Numeric;
  updated_at: Timestamp;
}

export interface PaymentsWebhooklog {
  created_at: Timestamp;
  error_message: string;
  event_type: string;
  gateway_id: Int8;
  id: Generated<Int8>;
  payload: Json;
  processed: boolean;
}

export interface PlatformopsFeatureflag {
  created_at: Timestamp;
  description: string;
  id: Generated<Int8>;
  is_enabled: boolean;
  key: string;
  name: string;
  updated_at: Timestamp;
  updated_by_id: Int8 | null;
}

export interface PlatformopsServermetricsnapshot {
  cpu_percent: number;
  disk_free_gb: number;
  disk_used_percent: number;
  id: Generated<Int8>;
  memory_percent: number;
  memory_total_mb: number;
  memory_used_mb: number;
  net_bytes_recv_mb: number;
  net_bytes_sent_mb: number;
  recorded_at: Timestamp;
}

export interface PlatformopsTaskheartbeat {
  id: Generated<Int8>;
  last_error: string;
  last_run_at: Timestamp | null;
  last_success: boolean | null;
  run_count: number;
  task_name: string;
}

export interface PropertyverificationsPropertyverification {
  ai_rationale: string;
  ai_risk_score: number | null;
  applicant_id: Int8;
  compliance_reviewed_at: Timestamp | null;
  compliance_reviewed_by_id: Int8 | null;
  created_at: Timestamp;
  deed_volume_number: string;
  due_diligence_done: boolean | null;
  id: Generated<Int8>;
  inspection_latitude: Numeric | null;
  inspection_longitude: Numeric | null;
  inspection_report: string | null;
  listing_id: Int8;
  mou_document: string | null;
  outcome_stage: string;
  owner_authorization_confirmed: boolean | null;
  owner_name: string;
  ownership_type: string;
  page_number: string;
  property_location: string;
  ps_reviewed_at: Timestamp | null;
  ps_reviewed_by_id: Int8 | null;
  resubmission_count: number;
  review_notes: string;
  status: string;
  supervisor_reviewed_at: Timestamp | null;
  supervisor_reviewed_by_id: Int8 | null;
  updated_at: Timestamp;
}

export interface RbacBreakglasssession {
  expires_at: Timestamp;
  granted_at: Timestamp;
  id: Generated<Int8>;
  reason: string;
  revoked_at: Timestamp | null;
  revoked_by_id: Int8 | null;
  user_id: Int8;
}

export interface RbacPendingapproval {
  action_key: string;
  created_at: Timestamp;
  decided_at: Timestamp | null;
  decided_by_id: Int8 | null;
  decision_reason: string;
  execution_error: string;
  execution_result: Json | null;
  id: Generated<Int8>;
  payload: Json;
  request_reason: string;
  requested_by_id: Int8;
  status: string;
}

export interface RbacRole {
  created_at: Timestamp;
  created_by_id: Int8 | null;
  description: string;
  id: Generated<Int8>;
  is_preset: boolean;
  name: string;
  slug: string;
  updated_at: Timestamp;
}

export interface RbacRolepermission {
  action: string;
  id: Generated<Int8>;
  resource: string;
  role_id: Int8;
}

export interface RbacUserroleassignment {
  granted_at: Timestamp;
  granted_by_id: Int8 | null;
  id: Generated<Int8>;
  role_id: Int8;
  user_id: Int8;
}

export interface ReportsReport {
  admin_notes: string;
  content_type: string;
  created_at: Timestamp;
  description: string;
  escalated_at: Timestamp | null;
  escalated_by_id: Int8 | null;
  escalation_notes: string;
  id: Generated<Int8>;
  owner_name: string;
  report_type: string;
  reported_listing_id: Int8 | null;
  reported_message_id: Int8 | null;
  reported_review_id: Int8 | null;
  reported_user_id: Int8 | null;
  reporter_id: Int8;
  resolved_at: Timestamp | null;
  resolved_by_id: Int8 | null;
  screenshot: string | null;
  status: string;
  updated_at: Timestamp;
}

export interface SuperadminAdminauditlog {
  action: string;
  actor_id: Int8 | null;
  created_at: Timestamp;
  id: Generated<Int8>;
  ip_address: string | null;
  metadata: Json;
  reason: string;
  target_id: string;
  target_repr: string;
  target_type: string;
  user_agent: string;
}

export interface SuperadminImpersonationsession {
  admin_id: Int8;
  ended_at: Timestamp | null;
  id: Generated<Int8>;
  ip_address: string | null;
  reason: string;
  started_at: Timestamp;
  target_id: Int8;
}

export interface SuperadminMfadevice {
  backup_codes: Json;
  confirmed: boolean;
  confirmed_at: Timestamp | null;
  created_at: Timestamp;
  id: Generated<Int8>;
  secret: string;
  user_id: Int8;
}

export interface SuperadminStaffeducation {
  created_at: Timestamp;
  degree: string;
  description: string;
  end_year: number | null;
  field_of_study: string;
  id: Generated<Int8>;
  institution: string;
  staff_id: Int8;
  start_year: number | null;
}

export interface SuperadminStafflegalrecord {
  created_at: Timestamp;
  document: string | null;
  document_number: string;
  expiry_date: Timestamp | null;
  id: Generated<Int8>;
  issue_date: Timestamp | null;
  issuing_authority: string;
  notes: string;
  record_type: string;
  staff_id: Int8;
  title: string;
}

export interface SuperadminStaffprofile {
  bio: string;
  created_at: Timestamp;
  department: string;
  hire_date: Timestamp | null;
  id: Generated<Int8>;
  is_active: boolean;
  onboarded_by_id: Int8 | null;
  phone_number: string;
  position: string;
  updated_at: Timestamp;
  user_id: Int8;
}

export interface SupportAircoverclaim {
  approved_amount: Numeric | null;
  booking_id: Int8;
  claim_type: string;
  claimant_id: Int8;
  created_at: Timestamp;
  description: string;
  id: Generated<Int8>;
  requested_amount: Numeric;
  review_notes: string;
  reviewed_at: Timestamp | null;
  reviewed_by_id: Int8 | null;
  status: string;
}

export interface SupportContactinquiry {
  category: string;
  conversation_id: Int8 | null;
  created_at: Timestamp;
  email: string;
  id: Generated<Int8>;
  is_read: boolean;
  message: string;
  name: string;
  subject: string;
  user_id: Int8 | null;
}

export interface SupportSupportticket {
  assigned_to_id: Int8 | null;
  category: string;
  conversation_id: Int8 | null;
  created_at: Timestamp;
  description: string;
  escalated_at: Timestamp | null;
  escalated_by_id: Int8 | null;
  escalation_notes: string;
  guest_email: string;
  guest_name: string;
  id: Generated<Int8>;
  priority: string;
  resolved_at: Timestamp | null;
  sla_due_at: Timestamp | null;
  status: string;
  subject: string;
  ticket_number: string;
  updated_at: Timestamp;
  user_id: Int8 | null;
}

export interface SupportTicketattachment {
  content_type: string;
  created_at: Timestamp;
  file: string;
  file_size: number;
  filename: string;
  id: Generated<Int8>;
  ticket_id: Int8;
  uploaded_by_id: Int8 | null;
}

export interface SupportTicketmessage {
  content: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  is_staff_reply: boolean;
  sender_id: Int8 | null;
  sender_name: string;
  ticket_id: Int8;
}

export interface SuspensionsSuspension {
  ends_at: Timestamp | null;
  id: Generated<Int8>;
  issued_by_id: Int8 | null;
  reason: string;
  related_report_id: Int8 | null;
  revocation_reason: string;
  revoked_at: Timestamp | null;
  revoked_by_id: Int8 | null;
  started_at: Timestamp;
  status: string;
  suspension_type: string;
  updated_at: Timestamp;
  user_id: Int8;
  user_notified: boolean;
}

export interface TestimonialsTestimonial {
  avatar_color: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  is_active: boolean;
  location: string;
  name: string;
  quote: string;
  rating: number;
  user_id: Int8 | null;
}

export interface TokenBlacklistBlacklistedtoken {
  blacklisted_at: Timestamp;
  id: Generated<Int8>;
  token_id: Int8;
}

export interface TokenBlacklistOutstandingtoken {
  created_at: Timestamp | null;
  expires_at: Timestamp;
  id: Generated<Int8>;
  jti: string;
  token: string;
  user_id: Int8 | null;
}

export interface TrustsafetyAccountsignupevent {
  created_at: Timestamp;
  id: Generated<Int8>;
  ip_address: string | null;
  user_id: Int8;
}

export interface TrustsafetyBlacklistedlocation {
  created_at: Timestamp;
  created_by_id: Int8 | null;
  id: Generated<Int8>;
  latitude: Numeric;
  longitude: Numeric;
  name: string;
  radius_km: Numeric;
  reason: string;
}

export interface TrustsafetyBlockedfingerprint {
  blocked_by_id: Int8 | null;
  created_at: Timestamp;
  fingerprint: string;
  id: Generated<Int8>;
  reason: string;
}

export interface TrustsafetyFraudflag {
  ai_rationale: string;
  ai_score: number | null;
  created_at: Timestamp;
  details: string;
  flag_type: string;
  id: Generated<Int8>;
  review_notes: string;
  reviewed_at: Timestamp | null;
  reviewed_by_id: Int8 | null;
  severity: string;
  status: string;
  user_id: Int8 | null;
}

export interface UsersMomochangerequest {
  created_at: Timestamp;
  email_otp: string;
  email_otp_expiry: Timestamp;
  email_otp_verified: boolean;
  id: Generated<Int8>;
  network_provider: string;
  new_momo_number: string;
  password_verified: boolean;
  sms_otp: string;
  sms_otp_expiry: Timestamp | null;
  sms_otp_verified: boolean;
  user_id: Int8;
}

export interface UsersPhonechangerequest {
  created_at: Timestamp;
  email_otp: string;
  email_otp_expiry: Timestamp;
  email_otp_verified: boolean;
  id: Generated<Int8>;
  network_provider: string;
  new_phone_number: string;
  password_verified: boolean;
  sms_otp: string;
  sms_otp_expiry: Timestamp | null;
  sms_otp_verified: boolean;
  user_id: Int8;
}

export interface UsersProfile {
  bio: string;
  id: Generated<Int8>;
  image: string | null;
  is_superhost: boolean;
  last_seen: Timestamp | null;
  phone_number: string;
  user_id: Int8;
}

export interface UsersUser {
  archived_at: Timestamp | null;
  date_joined: Timestamp;
  date_of_birth: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string;
  email_verification_token: string | null;
  email_verification_token_expires_at: Timestamp | null;
  email_verified: boolean;
  first_name: string;
  id: Generated<Int8>;
  is_active: boolean;
  is_archived: boolean;
  is_staff: boolean;
  is_superuser: boolean;
  last_login: Timestamp | null;
  last_name: string;
  password: string;
  password_reset_token: string | null;
  password_reset_token_expires_at: Timestamp | null;
  role: string;
  scheduled_deletion_at: Timestamp | null;
  username: string;
}

export interface UsersUserGroups {
  group_id: number;
  id: Generated<Int8>;
  user_id: Int8;
}

export interface UsersUserUserPermissions {
  id: Generated<Int8>;
  permission_id: number;
  user_id: Int8;
}

export interface DB {
  agents_agentapplication: AgentsAgentapplication;
  agents_agentcommission: AgentsAgentcommission;
  agents_agentprofile: AgentsAgentprofile;
  auth_group: AuthGroup;
  auth_group_permissions: AuthGroupPermissions;
  auth_permission: AuthPermission;
  authapp_blacklistedtoken: AuthappBlacklistedtoken;
  authapp_socialaccount: AuthappSocialaccount;
  bookings_booking: BookingsBooking;
  bookings_comparisonitem: BookingsComparisonitem;
  bookings_paymentrequest: BookingsPaymentrequest;
  bookings_propertycomparison: BookingsPropertycomparison;
  bookings_savedsearch: BookingsSavedsearch;
  bookings_searchalert: BookingsSearchalert;
  bookings_viewingappointment: BookingsViewingappointment;
  cache_table: CacheTable;
  chatbot_chatmessage: ChatbotChatmessage;
  chatbot_chatsession: ChatbotChatsession;
  django_admin_log: DjangoAdminLog;
  django_content_type: DjangoContentType;
  django_migrations: DjangoMigrations;
  django_session: DjangoSession;
  django_site: DjangoSite;
  hostapplications_agreementacceptance: HostapplicationsAgreementacceptance;
  hostapplications_hostapplication: HostapplicationsHostapplication;
  inventory_listingflag: InventoryListingflag;
  leaseagreements_leaseacceptance: LeaseagreementsLeaseacceptance;
  leaseagreements_leaseagreement: LeaseagreementsLeaseagreement;
  legalops_legaldocument: LegalopsLegaldocument;
  listings_favorite: ListingsFavorite;
  listings_hotelroom: ListingsHotelroom;
  listings_hotelroomimage: ListingsHotelroomimage;
  listings_listing: ListingsListing;
  listings_listingimage: ListingsListingimage;
  listings_listingsettings: ListingsListingsettings;
  listings_propertycategory: ListingsPropertycategory;
  listings_propertystats: ListingsPropertystats;
  listings_propertyview: ListingsPropertyview;
  listings_review: ListingsReview;
  listings_reviewimage: ListingsReviewimage;
  messaging_conversation: MessagingConversation;
  messaging_conversation_deleted_by: MessagingConversationDeletedBy;
  messaging_conversation_participants: MessagingConversationParticipants;
  messaging_message: MessagingMessage;
  messaging_messageattachment: MessagingMessageattachment;
  messaging_messageviolation: MessagingMessageviolation;
  newsletter_subscriber: NewsletterSubscriber;
  notifications_devicetoken: NotificationsDevicetoken;
  notifications_notification: NotificationsNotification;
  notifications_notificationpreference: NotificationsNotificationpreference;
  payments_currency: PaymentsCurrency;
  payments_employee: PaymentsEmployee;
  payments_employeepayment: PaymentsEmployeepayment;
  payments_escrowhold: PaymentsEscrowhold;
  payments_payment: PaymentsPayment;
  payments_paymentgateway: PaymentsPaymentgateway;
  payments_payout: PaymentsPayout;
  payments_platformfee: PaymentsPlatformfee;
  payments_refund: PaymentsRefund;
  payments_savedcard: PaymentsSavedcard;
  payments_striperefund: PaymentsStriperefund;
  payments_taxrate: PaymentsTaxrate;
  payments_webhooklog: PaymentsWebhooklog;
  platformops_featureflag: PlatformopsFeatureflag;
  platformops_servermetricsnapshot: PlatformopsServermetricsnapshot;
  platformops_taskheartbeat: PlatformopsTaskheartbeat;
  propertyverifications_propertyverification: PropertyverificationsPropertyverification;
  rbac_breakglasssession: RbacBreakglasssession;
  rbac_pendingapproval: RbacPendingapproval;
  rbac_role: RbacRole;
  rbac_rolepermission: RbacRolepermission;
  rbac_userroleassignment: RbacUserroleassignment;
  reports_report: ReportsReport;
  superadmin_adminauditlog: SuperadminAdminauditlog;
  superadmin_impersonationsession: SuperadminImpersonationsession;
  superadmin_mfadevice: SuperadminMfadevice;
  superadmin_staffeducation: SuperadminStaffeducation;
  superadmin_stafflegalrecord: SuperadminStafflegalrecord;
  superadmin_staffprofile: SuperadminStaffprofile;
  support_aircoverclaim: SupportAircoverclaim;
  support_contactinquiry: SupportContactinquiry;
  support_supportticket: SupportSupportticket;
  support_ticketattachment: SupportTicketattachment;
  support_ticketmessage: SupportTicketmessage;
  suspensions_suspension: SuspensionsSuspension;
  testimonials_testimonial: TestimonialsTestimonial;
  token_blacklist_blacklistedtoken: TokenBlacklistBlacklistedtoken;
  token_blacklist_outstandingtoken: TokenBlacklistOutstandingtoken;
  trustsafety_accountsignupevent: TrustsafetyAccountsignupevent;
  trustsafety_blacklistedlocation: TrustsafetyBlacklistedlocation;
  trustsafety_blockedfingerprint: TrustsafetyBlockedfingerprint;
  trustsafety_fraudflag: TrustsafetyFraudflag;
  users_momochangerequest: UsersMomochangerequest;
  users_phonechangerequest: UsersPhonechangerequest;
  users_profile: UsersProfile;
  users_user: UsersUser;
  users_user_groups: UsersUserGroups;
  users_user_user_permissions: UsersUserUserPermissions;
}
