# Generated by Django 5.2.13 on 2026-06-19 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_viewingappointment_and_more'),
        ('payments', '0006_platformfee_service_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('booking', 'Booking / Rent'), ('viewing_fee', 'Viewing Appointment Fee')], default='booking', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='viewing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.viewingappointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking'),
        ),
    ]
