# Generated by Django 5.2.16 on 2026-07-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_striperefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='reason_code',
            field=models.CharField(choices=[('misrepresentation', 'Property misrepresentation'), ('legal_issue', 'Legal issue discovered'), ('safety_concern', 'Safety concern'), ('change_of_mind', 'Change of mind (not eligible)'), ('other', 'Other (admin discretion)')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='striperefund',
            name='reason_code',
            field=models.CharField(choices=[('misrepresentation', 'Property misrepresentation'), ('legal_issue', 'Legal issue discovered'), ('safety_concern', 'Safety concern'), ('change_of_mind', 'Change of mind (not eligible)'), ('other', 'Other (admin discretion)')], default='other', max_length=20),
        ),
    ]
