# Generated by Django 5.2.13 on 2026-08-21 01:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_refund_reason_code_striperefund_reason_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='recipient_momo_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='payout',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payout',
            name='recipient_network',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='platformfee',
            name='agent_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text="Sourcing-agent commission, as a percent of the booking rent, paid on agent-sourced bookings. Default 0.50 = 0.5% of the rent (i.e. 25% of the platform's 2% net guest-side fee).", max_digits=5),
        ),
    ]
