# Generated by Django 5.2.13 on 2026-09-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payout_recipient_momo_number_payout_recipient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformfee',
            name='booking_fee',
        ),
    ]
