#!/usr/bin/env bash
# Creates express-backend/.env for the standby Express backend from the
# Django backend's backend/.env. Shared third-party settings (Stripe, MoMo,
# Brevo, Google, VAPID, DJANGO_SECRET_KEY for JWT compatibility, ...) are
# copied as-is; everything that would make the two backends touch each
# other's infrastructure (database, Redis, media) is overridden to point at
# the Express-only services. See express-backend/README.md.
#
# Usage: bash scripts/express-init-env.sh [--force]
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT_DIR/backend/.env"
DST="$ROOT_DIR/express-backend/.env"

if [[ -e "$DST" && "${1:-}" != "--force" ]]; then
  echo "$DST already exists — re-run with --force to regenerate (this rotates the Express DB password," >&2
  echo "which only works before express-db has been initialised, or after 'docker volume rm'ing its data)." >&2
  exit 1
fi
[[ -r "$SRC" ]] || { echo "Cannot read $SRC" >&2; exit 1; }
mkdir -p "$(dirname "$DST")"

OVERRIDDEN='^(POSTGRES_HOST|POSTGRES_PORT|POSTGRES_DB|POSTGRES_USER|POSTGRES_PASSWORD|POSTGRES_SSLMODE|POSTGRES_CHANNEL_BINDING|POSTGRES_CONN_MAX_AGE|DB_ENGINE|REDIS_URL|CELERY_ALWAYS_EAGER|MEDIA_ROOT|EXPRESS_[A-Z_]+)='

DB_PASSWORD="$(openssl rand -hex 24)"
umask 077
{
  echo "# Generated by scripts/express-init-env.sh from backend/.env on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# Shared third-party settings are copied from the Django backend; infrastructure is Express-only."
  echo
  echo "# --- Copied from backend/.env -------------------------------------------"
  grep -Ev "$OVERRIDDEN" "$SRC" | grep -Ev '^\s*#|^\s*$'
  echo
  echo "# --- Express-only infrastructure (never Django's) ------------------------"
  echo "POSTGRES_HOST=express-db"
  echo "POSTGRES_PORT=5432"
  echo "POSTGRES_DB=homekonet"
  echo "POSTGRES_USER=homekonet_express"
  echo "POSTGRES_PASSWORD=$DB_PASSWORD"
  echo "REDIS_URL=redis://express-redis:6379/0"
  echo "MEDIA_ROOT=/app/media"
  echo
  echo "# Background jobs (emails, reservation expiry, payout reconciliation, ...)."
  echo "# Keep false while Express is on standby so jobs never run twice;"
  echo "# scripts/switch-backend.sh flips it when Express becomes active."
  echo "EXPRESS_JOBS_ENABLED=false"
} > "$DST"
chmod 600 "$DST"

# express-db only needs these three — kept in their own file so the database
# container's environment doesn't carry every API key.
printf 'POSTGRES_USER=homekonet_express\nPOSTGRES_PASSWORD=%s\nPOSTGRES_DB=homekonet\n' "$DB_PASSWORD" > "$DST.db"
chmod 600 "$DST.db"
echo "Wrote $DST and $DST.db (mode 600)."
