# Generated by Django 5.2.13 on 2026-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_review_reviewimage_propertystats_propertyview"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="listing",
            name="bathrooms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="beds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="booking_mode",
            field=models.CharField(
                choices=[
                    ("instant", "Instant book"),
                    ("approve_first", "Approve first"),
                ],
                default="instant",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="exterior_camera",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="highlights",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="listing",
            name="last_minute_discount_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="last_minute_discount_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="max_guests",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="listing",
            name="monthly_discount_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="monthly_discount_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="new_listing_promo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="noise_monitor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="privacy_type",
            field=models.CharField(
                choices=[
                    ("entire_place", "Entire place"),
                    ("private_room", "Private room"),
                    ("shared_room", "Shared room"),
                ],
                default="entire_place",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="weapons_on_property",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="weekend_premium_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="weekly_discount_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="weekly_discount_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="listing",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("cabin", "Cabin"),
                    ("cottage", "Cottage"),
                    ("bungalow", "Bungalow"),
                    ("chalet", "Chalet"),
                    ("treehouse", "Treehouse"),
                    ("boat", "Boat"),
                    ("castle", "Castle"),
                    ("cave", "Cave"),
                    ("farm", "Farm"),
                ],
                max_length=50,
            ),
        ),
    ]
