# Generated by Django 5.2.13 on 2026-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_listing_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="cancellation_policy",
            field=models.CharField(
                choices=[
                    ("flexible", "Flexible"),
                    ("moderate", "Moderate"),
                    ("strict", "Strict"),
                    ("super_strict", "Super Strict"),
                ],
                default="flexible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="accuracy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="check_in_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="cleanliness",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="communication",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="host_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="review",
            name="host_response_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="location_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
