# Generated by Django 5.2.13 on 2026-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_add_new_property_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=20),
        ),
    ]
