# Generated by Django 5.2.13 on 2026-06-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lease_term_months',
            field=models.PositiveIntegerField(blank=True, choices=[(6, '6 months'), (12, '1 year'), (24, '2 years'), (36, '3 years')], help_text='Lease length for long-term (monthly) listings — sets the booking end date.', null=True),
        ),
    ]
