# Generated by Django 5.2.16 on 2026-07-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_listing_suspended_at_listing_suspended_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='local_registration_number',
            field=models.CharField(blank=True, help_text='Local business/short-term-rental registration or license number.', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='occupancy_cap',
            field=models.PositiveIntegerField(blank=True, help_text='Legal maximum occupancy for this address. max_guests may not exceed this once set.', null=True),
        ),
    ]
