# Generated by Django 5.2.16 on 2026-08-08 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_listing_local_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_monthly_price', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Minimum price (USD) a listing can be created or saved with. Enforced both in the create-listing wizard and server-side.', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Listing Settings',
                'verbose_name_plural': 'Listing Settings',
            },
        ),
    ]
