# Generated by Django 5.2.13 on 2026-08-21 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listing_agent_owner_email_listing_agent_owner_name_and_more'),
        ('listings', '0023_listingsettings'),
    ]

    operations = [
    ]
