# Generated by Django 5.2.16 on 2026-08-08 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lease_term_months',
            field=models.PositiveIntegerField(blank=True, help_text='Lease length in months for long-term (monthly) listings — sets the booking end date. Any positive number of months is allowed (the wizard offers 1/6/12/24/36-month presets plus a custom "Other" option).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
