# Generated by Django 5.2.13 on 2026-09-04 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0024_alter_listing_lease_term_months"),
        ("listings", "0024_merge_20260821_1927"),
    ]

    operations = []
