from django.urls import path
from . import views

urlpatterns = [
    path('initiate/', views.initiate_payment, name='initiate_payment'),
    path('viewing/initiate/', views.initiate_viewing_payment, name='initiate_viewing_payment'),
    path('verify/', views.verify_payment, name='verify_payment'),
    path('refund/', views.process_refund, name='process_refund'),
    path('user/', views.user_payments, name='user_payments'),
    path('admin/payouts/', views.admin_payouts, name='admin_payouts'),
    path('admin/payouts/<uuid:payout_id>/mark-paid/', views.admin_mark_payout_paid, name='admin_mark_payout_paid'),
    path('admin/payouts/<uuid:payout_id>/cancel/', views.admin_cancel_payout, name='admin_cancel_payout'),
    path('admin/refund/', views.admin_refund_payment, name='admin_refund_payment'),
    path('admin/stripe-refund/', views.admin_stripe_refund, name='admin_stripe_refund'),
    path('admin/platform-fee/', views.admin_platform_fee, name='admin_platform_fee'),
    path('admin/reports/summary/', views.admin_financial_summary, name='admin_financial_summary'),
    path('admin/transactions/', views.admin_transactions_list, name='admin_transactions_list'),
    path('admin/transactions/export/', views.admin_transactions_export, name='admin_transactions_export'),
    path('admin/escrow/', views.admin_escrow_list, name='admin_escrow_list'),
    path('admin/escrow/<int:booking_id>/hold/', views.admin_escrow_hold, name='admin_escrow_hold'),
    path('admin/escrow/<int:hold_id>/release/', views.admin_escrow_release, name='admin_escrow_release'),
    path('admin/tax-rates/', views.admin_tax_rates, name='admin_tax_rates'),
    path('admin/tax-rates/<int:pk>/', views.admin_tax_rate_detail, name='admin_tax_rate_detail'),
    path('admin/tax-report/', views.admin_tax_report, name='admin_tax_report'),
    path('<uuid:payment_id>/', views.payment_detail, name='payment_detail'),
    path('webhooks/mtn_momo/', views.mtn_momo_webhook, name='mtn_momo_webhook'),
    path('webhooks/stripe/', views.stripe_webhook, name='stripe_webhook'),
    path('stripe/payment-intent/', views.create_stripe_payment_intent, name='stripe_payment_intent'),
    path('stripe/booking-payment-intent/', views.create_booking_payment_intent, name='stripe_booking_payment_intent'),
    path('stripe/booking-fee-intent/', views.create_booking_fee_intent, name='stripe_booking_fee_intent'),
    path('stripe/viewing-fee-intent/', views.create_viewing_fee_intent, name='stripe_viewing_fee_intent'),
    path('cards/', views.saved_cards, name='saved_cards'),
    path('cards/<int:card_id>/', views.saved_card_detail, name='saved_card_detail'),
]