# Generated by Django 5.2.13 on 2026-06-16 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have soft-deleted this conversation from their inbox.', related_name='deleted_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
