# Generated by Django 5.2.8 on 2026-01-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('agent', 'Agent'), ('admin', 'Admin')], default='user', max_length=15),
        ),
    ]
