# Generated by Django 5.2.8 on 2026-03-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_momo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='momo_number',
            field=models.CharField(blank=True, help_text='MTN Mobile Money number for receiving payouts (Liberian format, e.g. 0880123456)', max_length=20),
        ),
    ]
