# Generated by Django 5.2.13 on 2026-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_phonechangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_superhost",
            field=models.BooleanField(default=False),
        ),
    ]
