# Generated by Django 5.2.16 on 2026-07-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_options_user_unique_lower_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('agent', 'Agent'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], default='user', max_length=15),
        ),
    ]
